version: '3'

services:
  db:
    image: postgres:9.6.8
  redis:
    image: redis:3.2.11
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
